### PR TITLE
Cross-platform support

### PR DESCRIPTION
**Pull request by laqieer**
[MacOS & Linux Release](https://github.com/laqieer/ColorzCore/releases/latest)

### CODE REVIEW

**Comment by Crazycolorz5** [comment]
This PR has been reverted in #50. 

I couldn't get Visual Studio (2017) to produce an executable output that I could run correctly.
Please configure it so that a `.exe` is produced in the `bin/Release` directory, then create a new PR.

**Comment by laqieer** [comment]
.Net Core 3.1 (LTS) (recommended)'s default output directoty is `bin/Release/netcoreapp3.1` and the default publish directoty is `bin/Release/netcoreapp3.1/publish`. Specific platform's default output (such as `.exe` for win) is `bin/Release/netcoreapp3.1/{platform}` and `bin/Release/netcoreapp3.1/{platform}/publish`.
.Net Core 3+ SDK needs Visual Studio 2019 and .Net Core 3.1.1 SDK is already included in Visual Studio 16.4.3. Visual Studio 2017 supports .Net Core 2.1 (15.9) or .Net Core 2.1 (15.7).
Please choose any of these ossible solutions:
1. Upgrade Visual Studio.
1. Build project with dotnet CLI.
1. Downgrade .Net Core.

**Comment by Crazycolorz5** [comment]
I did downgrade .net core (to 2.0), but I wasn't able to get the compiled executable to properly function; 

`The managed DLL bound to this executable: 'ColorzCore.dll', did not match own name 'Core.dll'.
A fatal error was encountered. This executable was not bound to load a managed DLL.`

Is there a way to get it to compile without having to be distributed with a DLL?

**Comment by laqieer** [comment]
idk the way to distribute netcoreapp without dll.
Please read the [official doc](https://docs.microsoft.com/en-us/dotnet/core/deploying/index) for distribution detail.

**Comment by Crazycolorz5** [comment]
In any case, I don't want to keep this merged with the `master` branch unless we can have a standalone executable (ideally built as `bin/Release/ColorzCore.exe`) in the repository.

**Comment by laqieer** [comment]
Google it.
According to [this](https://gunnarpeipman.com/dotnet-core-self-contained-executable/), you can try build option `/p:PublishSingleFile=true`.
According to [this](https://www.hanselman.com/blog/MakingATinyNETCore30EntirelySelfcontainedSingleExecutable.aspx), you can try config `<PublishTrimmed>true</PublishTrimmed>` or command `dotnet warp`.

**Pull request merged**
